### ISSUE TITLE
No index on Event and EventPath table

### ISSUE THREAD

**Issue by daikeshi** [google/ml-metadata#106]
When data size grows in MLMD, we hit some performance issues mainly caused by `Event` and `EventPath` table. 

In TFX metadata layer, [get_events_by_artifact_ids](https://github.com/tensorflow/tfx/blob/463586187bf0cdc1e7290f27bf5096d2f13f1593/tfx/orchestration/metadata.py#L834) and [get_events_by_execution_ids](https://github.com/tensorflow/tfx/blob/463586187bf0cdc1e7290f27bf5096d2f13f1593/tfx/orchestration/metadata.py#L868) are called and they query `Event` table by `artifact_id` and `EventPath` table by `event_id`. However, both `artifact_id` and `event_id` columns are not indexed in those two tables. This caused us significant query performance issues sicne we have a lot of executions and events in MLMD.

**Comment by hughmiao** [comment]
@daikeshi , if not yet, please use release > 0.25, we add Event indices in schema v6, please see [1] and [2] for details. 

[1] https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md#resources
[2] https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md#resources

**Comment by daikeshi** [comment]
Thanks @hughmiao for the info, but I think `EventPath` needs an index too. This table is even bigger than `Event` table.

**Comment by hughmiao** [comment]
@daikeshi yes, will add it in the next schema change, currently the EventPath does scan with `in`. Before the schema v7, please consider to create a custom index on eventpath event_id with namespace-prefixed names.
