### ISSUE TITLE
RuntimeError: Error when executing query: file is not a database query

### ISSUE THREAD

**Issue by ird-tue** [google/ml-metadata#109]
Any idea what am I missing here?

**Comment by ird-tue** [comment]
> Any idea what am I missing here?

RuntimeError: Error when executing query: file is not a database query:  CREATE TABLE IF NOT EXISTS `Type` (    `id` INTEGER PRIMARY KEY AUTOINCREMENT,    `name` VARCHAR(255) NOT NULL,    `version` VARCHAR(255),    `type_kind` TINYINT(1) NOT NULL,    `description` TEXT,    `input_type` TEXT,    `output_type` TEXT );

**Comment by hughmiao** [comment]
'file is not a database query' is thrown from sqlite3: it looks connection config used a filename_uri that cannot be opened by the sqlite lib. consider to examine the path, or try to use another local path.
