### ISSUE TITLE
next_page_token in GetArtifactsByContextResponse becomes very large

### ISSUE THREAD

**Issue by ricardodirecto** [google/ml-metadata#120]
Hello team!

In ml-metadata 0.28.0 the next_page_token seems to grow unbounded with every next page to be hundreds of megabytes in size. This seems to indicate an issue, unless I missed something. Consider this code snippet:

```
!pip install ml-metadata==0.28.0
 
import ml_metadata
from ml_metadata.proto import metadata_store_pb2
from ml_metadata.proto import metadata_store_service_pb2
 
def get_mlmd_client(
  grpc_host: str = 'metadata-grpc-service.kubeflow',
  grpc_port: int = 8080,
  grpc_max_receive_message_length: int = -1
):
  return ml_metadata.MetadataStore(
    metadata_store_pb2.MetadataStoreClientConfig(
      host=grpc_host,
      port=grpc_port,
      channel_arguments=metadata_store_pb2.GrpcChannelArguments(
        max_receive_message_length=grpc_max_receive_message_length
      )
    )
  )
 
client = get_mlmd_client()
 
request = metadata_store_service_pb2.GetArtifactsByContextRequest()
request.context_id = 21005
request.options.max_result_size = 10
request.options.order_by_field.field = (
  metadata_store_pb2.ListOperationOptions.OrderByField.Field.CREATE_TIME
)
request.options.order_by_field.is_asc = False
 
while True:
  response = metadata_store_service_pb2.GetArtifactsByContextResponse()
  client._call('GetArtifactsByContext', request, response)
  print(len(response.next_page_token))
  if not response.next_page_token:
    break
  request.options.next_page_token = response.next_page_token
```

This prints token sizes:

```
28
68
122
195
294
426
602
836
1148
1564
2119
2859
3846
5162
6916
9255
12374
16532
22079
29475
39336
52484
70015
93390
124556
166111
221518
295394
393895
525230
700343
933827
1245139
1660222
2213666
2951594
3935498
5247370
6996532
9328748
12438370
16584532
22112748
29483703
39311643
52415563
69887456
93183314
124244458
165659316
220879127
294505542
392674098
```

Thank you!

**Comment by hughmiao** [comment]
thanks for reporting this issue, @ricardodirecto, it looks the current implementation encode the previous request as the next page token, which in turns increase the size over requests. let's fix this in the coming release.

/cc KFP folks @dushyanthsc @neuromage

**Comment by ricardodirecto** [comment]
Thank you for the quick fix!

I forgot to mention that when this happens eventually the server crashes with this error:
```
assertion failed: byte_count_ < total_size_
```

The server restarts itself and in that minute or so it takes for it to restart, metadata-grpc is unavailable to other pipelines that are marked failed if they need to access it during that time.

Would it be possible to release this fix as a minor version?

Thank you!

**Comment by hughmiao** [comment]
it will be released in 1.1.

**Comment by rafaelbarreto87** [comment]
@hughmiao would be safe to upgrade the server from 0.28.0 straight to this version or does it require backwards incompatible schema migrations?

We're currently running 0.28.0 as part of a Kubeflow deployment and running into this problem where some queries are crashing the server and disrupting other completely independent jobs that also query ML metadata. So it's somewhat urgent for us to "fix" it, but I'm concerned that upgrading to this version might break other things.

**Comment by hughmiao** [comment]
if all your access to the db are via the server, then it is safe to upgrade server to use the latest version, while keeping the client libraries using the 0.28.0. The RPCs are backward compatible. 

When upgrading server, the schema migration is needed, please pass the upgrade [flag](https://github.com/google/ml-metadata/blob/d686149549d6b35e6bd4ef7802db597eb131e07d/ml_metadata/metadata_store/metadata_store_server_main.cc#L185) when starting the new version server.

**Comment by rafaelbarreto87** [comment]
@hughmiao thanks for the answer. That's good to hear. In case anything goes wrong with the schema migration, is it possible to undo it (we will also have backups of course, but just tryring to assess the risk)?

**Comment by hughmiao** [comment]
yes, you can use the new server to downgrade to v6, by using the [flag](https://github.com/google/ml-metadata/blob/d686149549d6b35e6bd4ef7802db597eb131e07d/ml_metadata/metadata_store/metadata_store_server_main.cc#L188), and switch back to old server.
