### ISSUE TITLE
Support for Microsoft SQL Server?

### ISSUE THREAD

**Issue by GaniMarquez** [google/ml-metadata#122]
Are there plans on supporting other transactional databases like MSSQL? We are currently considering MLMD as part of our stack as we build our ML pipeline. However, we are currently blocked by the options we have on how to persist the data. Thank you. 😄

**Comment by hughmiao** [comment]
consider to fork and build a custom source? it is difficult to cover mssql in continuous releases. please see earlier threads about extension (https://github.com/google/ml-metadata/issues/17#issuecomment-538192251)
