### ISSUE TITLE
Updating schema in mlmd server

### ISSUE THREAD

**Issue by dwsmith1983** [google/ml-metadata#125]
System:

- Mac OSX BigSur 11.4 and Databricks 8.4 runtime on GCP
- Python 3.8
- ml-metadata==1.0.0
- tfx==1.0.0
- tfdv==1.0.0
- tf==2.5.0

With `tensorflow_data_validation`, we have update actions for the schema. This article show `tdfv` [GCP analyzing and validating at scale TFX](https://cloud.google.com/architecture/analyzing-and-validating-data-at-scale-for-ml-using-tfx) but I guess I am struggling to connect where `mlmd` fits in. 

1. Is the same possible with `ml-metadata`? 

That is, after I run SchemaGen, I can apply updates to the schema in the mlmd server? This is a production server not a local instants. 

2. If `mlmd` doesn't have this ability, can `tfdv` push schema updates to `mlmd`? 

Also, if SchemaGen, from a `mlmd` run, identifies a categorical column as int column, since it hasn't been one-hot encoded yet, can I update the schema to categorical on this variable (and should I update here)?

The workflow is input data -> ExampleGen -> SchemaGen and StatisticGen -> ExampleValidator -> Transformations
I am not using`tf` as part of the transformations. I am using `mlmd` and `tfdv` standalone as part of ML pipeline not reliant on TF so the transformations happen in Spark but we are using `mlmd` for metadata tracking.

Should I correct a data issues such as int column needing to be categorical? Or should I run again Example -> .... -> ExampleValidator after applying the transformations?

Or is the assumption `mlmd` only uses refined features from a feature store so the input data shouldn't have any issues with SchemaGen?

**Comment by hughmiao** [comment]
A schema of tfdv is a payload file in tfx systems, and not related to  ml-metadata. 
mlmd in this case, tracks the schema as an artifact published by the workflow, and the artifact uri pointing to the physical schema. mlmd also tracks which schemagen run produces that artifact. 
See [1] for some example, and consider to elaborate the question and post to tfx for tfdv usage.

[1] https://www.tensorflow.org/tfx/tutorials/tfx/penguin_tfdv

**Comment by dwsmith1983** [comment]
> A schema of tfdv is a payload file in tfx systems, and not related to ml-metadata.
> mlmd in this case, tracks the schema as an artifact published by the workflow, and the artifact uri pointing to the physical schema. mlmd also tracks which schemagen run produces that artifact.
> See [1] for some example, and consider to elaborate the question and post to tfx for tfdv usage.
> 
> [1] https://www.tensorflow.org/tfx/tutorials/tfx/penguin_tfdv

This doesn't address anything I asked about it. Why would you close this prematurely?
