### ISSUE TITLE
Support py.typed

### ISSUE THREAD

**Issue by peteboothroyd** [google/ml-metadata#127]
It would be nice if ml-metadata exposed its type information to clients, like:

https://github.com/tensorflow/tfx/pull/3981

See [PEP-561](https://www.python.org/dev/peps/pep-0561/) for more details.

Concretely this just means adding an empty file called `py.typed` at the root of the package.

**Comment by BrianSong** [comment]
Hi peteboothroyd, 

Thanks for raising up this issue.

To clarify, are you having some problems without ml_metadata exposing its type information?

**Comment by peteboothroyd** [comment]
The problem is that although ml-metadata has type annotated its public api this is not checked by clients which use tools such as mypy, so clients aren't getting the benefits provided by type checking their usage of ml-metadata.
