### ISSUE TITLE
MySQL client does not support caching_sha2_password

### ISSUE THREAD

**Issue by peteboothroyd** [google/ml-metadata#128]
MySQL 8 uses caching_sha2_password by default. The currently used mysql client ([mariadb-connector-c](https://mariadb.com/kb/en/mariadb-connector-c-308-release-notes/)) supports this in the release which ml-metadata uses. However when trying to connect to a MySQL database which uses caching_sha2_password throws an error `RuntimeError: mysql_real_connect failed: errno: 0, error:`. Changing authentication to mysql_native_password works around the problem. It would be nice if we could use the more secure authentication method.

**Comment by BrianSong** [comment]
Hi peteboothroyd,

Thanks for bringing this up to our notice.

Currently changing the MySQL client is not in this Q's roadmap, especially given that the common workaround "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';" + "flush privileges;" could fix the error. 

Close this issue for now.
