### ISSUE TITLE
Can't import metadata_store_service_pb2_grpc

### ISSUE THREAD

**Issue by TomomasaTakatori** [google/ml-metadata#13]
I try to use the grpc connection,  but can't.
Error is "ImportError: cannot import name 'metadata_store_service_pb2_grpc'"

**Comment by hughmiao** [comment]
In the current release, the python client stub is not included in the repo and the released pip wheel. It needs to be generated by the user. Please see [https://github.com/google/ml-metadata/pull/5](url) for reference to generate the client stub. In future release, there are plans to simplify the grpc connection and include in the release directly.

**Comment by TomomasaTakatori** [comment]
Sure.
Thank you for your  replying!
