### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by chensun** [google/ml-metadata#139]
Setup.py requirements indicates it should support Python 3.9
https://github.com/google/ml-metadata/blob/c28a77f0d34cabea675d119bc23a1c2174293b75/setup.py#L157

However, there's no wheel for 3.9 released:
https://pypi.org/project/ml-metadata/1.5.0/#files

I took a quick look at the dependency packages, all of them seems to support Python 3.9. Is there something blocking ml-metadata from supporting Python 3.9, or it's just a miss in release configuration?

**Comment by BrianSong** [comment]
Hi Chen Sun,

Yes, MLMD supports Python 3.9. Let me check with our release team on this. Thanks for bringing this to our notice!

**Comment by BrianSong** [comment]
After checking with our release team, MLMD will not proceed with Python 3.9 support until Apache Beam support Python 3.9, and it seems that they have not support it yet: https://pypi.org/project/apache-beam/2.35.0/#files.

Let's keep this issue open and resolve it after MLMD officially support Python 3.9.

**Comment by chensun** [comment]
Thanks for the reply @BrianSong. 

I'm not sure why apache-beam is in the way. It's a not a dependency per se: 
https://github.com/google/ml-metadata/blob/c28a77f0d34cabea675d119bc23a1c2174293b75/setup.py#L150-L156

**Comment by BrianSong** [comment]
As internally, MLMD will be released together with TFX-related teams. As some of the TFX-related teams depend on apache beam, our release team decided to support python 3.9 after apache beam to avoid confusion.

**Comment by alexjajones** [comment]
Hey @BrianSong 👋  Apache Beam now supports Python `3.9` [2.37.0](https://github.com/apache/beam/releases/tag/v2.37.0), is it possible to update the MLMD to also support? Let me know if I can help in anyway. Thanks!

**Comment by BrianSong** [comment]
Hi @alexjajones, thanks for letting us know. Let me talk to the internal release team.

**Comment by BrianSong** [comment]
From the internal release team: will be supporting py39 for TFX libs from next release train i.e 
TFX 1.8.0/0.39.0.

**Comment by CandiedCode** [comment]
@BrianSong I see that ml-metadata was updated to support [python 3.9](https://github.com/google/ml-metadata/commit/c435135ece2f239a85350b15f5ce4e56d6c62c3f).

However, it doesn't look like pybind11 was updated.  ml-metadata is currently using [2.4.3](https://github.com/google/ml-metadata/blob/master/WORKSPACE#L122) but python 3.9 support wasn't fully supported until [2.6.0](https://github.com/pybind/pybind11/releases/tag/v2.6.0rc1)

**Comment by XinranTang** [comment]
@CandiedCode MLMD now supports Python 3.10 and pybind11 2.10. I am going to close this issue :)
