### ISSUE TITLE
Inconsistent documentation for DB schema versions

### ISSUE THREAD

**Issue by hvy** [google/ml-metadata#146]
The DB schema version was upgraded to 8 in 1.7.0, but is inconsistently documented. 
Assuming that the upgrade was intended, it'd be great if we could update the documentation to be consistent, to avoid unnecessary confusion.

Inconsistent documentation that I stumbled upon are the following.

- `get_started.md` https://github.com/google/ml-metadata/blob/v1.7.0/g3doc/get_started.md
  - Actual: Schema versions are 7 for both 1.6.0 and 1.7.0 (and other older versions). Nothing about schema version 8 is mentioned.
    - Related commit https://github.com/google/ml-metadata/commit/18b27392853f2028946636b2f4eca078062de044
  - Expected: 1.6.0: 7, and 1.7.0: 8.
- `RELEASE.md` https://github.com/google/ml-metadata/blob/master/RELEASE.md
  - Actual: Schema version 8 introduced in 1.6.0
    - Although I'm not sure how this file is maintained, looks unintentional.
    - Related commit https://github.com/google/ml-metadata/commit/8772404b36bc75a868c5cc0c75acccb27612d7de
  - Expected: Schema version 8 introduced in 1.7.0.
- Release notes https://github.com/google/ml-metadata/releases
  - Actual: Nothing about schema version 8 is mentioned.
  - Expected: Schema version 8 introduced in 1.7.0.

I'd be happy to send PRs if that could be of any help. Thanks!

**Comment by BrianSong** [comment]
@hvy Thanks for pointing this out! This is indeed an internal oversight. Fixing this issue right now.
