### ISSUE TITLE
When supports for attrs version >21 is available?

### ISSUE THREAD

**Issue by amirhessam88** [google/ml-metadata#159]
Currently, ml-metadata (1.9.0) depends on attrs (>=20.3,<21) and this raises a lot of incompatibility of other wrappers on top of ml-metadata. I am wondering when the support for attrs > 21 is available?

**Comment by BrianSong** [comment]
Hi @amirhessam88, could you be more specific about the wrappers on top of ml-metadata that causing the incompatibility? That could help us be more clear about the situation.

**Comment by amirhessam88** [comment]
Hey @BrianSong ; some growing libraries such as [ZenML](https://github.com/zenml-io/zenml) depends on `ml-pipelines-sdk` and accordingly that depends on `ml-metadata`; at the same time, if another projects requires `attrs >=21` that would create a dependency conflict. does that make sense?

**Comment by BrianSong** [comment]
I see. 

However, ml_metadata has the version constraint in order to be sync with TFX as shown in [1].

Let me talk to the TFX folks to see if they can bump that version. 

[1] https://github.com/tensorflow/tfx/blob/b021a486c9363147eca35e97742b555a5ad1cce4/tfx/dependencies.py#L77

**Comment by amirhessam88** [comment]
@BrianSong Sounds good. Thanks

**Comment by BrianSong** [comment]
Hi, @amirhessam88, I bump the limit to <22 so that at least 21.X. attrs version can be supported. The reason why I cannot bump the version higher is because our internal attrs only support <22 and we need to keep that in sync.

**Comment by amirhessam88** [comment]
Hey @BrianSong ; I totally understand the reasonings and really appreciate it. 🙏

**Comment by BrianSong** [comment]
Closing this issue right now and please feel free to reopen it if this does not work for you.
