### ISSUE TITLE
Cannot install ml-metadata v1.0.0

### ISSUE THREAD

**Issue by AlexandreBrown** [google/ml-metadata#161]
# Description  
Hello, I cannot install `v1.0.0` of ml-metadata using pip even tho the version seems available on the PyPi page : .  https://pypi.org/project/ml-metadata/#history
![Screenshot from 2022-07-20 07-17-46](https://user-images.githubusercontent.com/26939775/179969378-d6fd06e9-f96b-4857-9ee3-9eb276f56121.png)  
  
# Use Case  
- Use `ml_metadata` to acces Kubeflow artifacts information stored in the MySQL db.

**Comment by codesue** [comment]
I get similar errors when trying to install `ml-metadata<1.10.0,>=1.9.0` for Python 3.9.7 on a machine with an Apple M1 Pro chip, but installation works without errors on an Intel chip.

```console
ERROR: Could not find a version that satisfies the requirement ml-metadata<1.10.0,>=1.9.0 (from tfx<2.0.0,>=1.8.0->streamlit-tfx) (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0)
ERROR: No matching distribution found for ml-metadata<1.10.0,>=1.9.0 (from tfx<2.0.0,>=1.8.0->streamlit-tfx)
```

**Comment by AlexandreBrown** [comment]
@codesue Interesting, I have an AMD CPU but I feel like for me the issue is finding the package on PyPi when doing a pip install.  
Could you paste in your pip command ? Maybe there are flags that I'm not aware of to find the package.

**Comment by codesue** [comment]
@AlexandreBrown I'm doing a regular pip install with the default resolver and no flags, e.g. `pip install ml-metadata==1.9.0`.

On an M1 Pro chip using Python 3.9.7, this produces the error:
```console
ERROR: Could not find a version that satisfies the requirement ml-metadata==1.9.0 (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0)
ERROR: No matching distribution found for ml-metadata==1.9.0
```

**Comment by AlexandreBrown** [comment]
@codesue Ok, yes installing the latest version works for me as well being on a x86 architecture cpu, can you try to install v1.0.0 on both your machines to see if you have the same issue as me?

**Comment by codesue** [comment]
@AlexandreBrown Ohhh, `1.0.0` doesn't install on either. Not related to https://github.com/google/ml-metadata/issues/143.

**Comment by BrianSong** [comment]
@AlexandreBrown Thanks for bringing this up. What version of `pip` are you using?

**Comment by AlexandreBrown** [comment]
Hello @BrianSong , I'm using pip version `21.2.4` (was also able to reproduce on latest version `22.2.1`

**Comment by BrianSong** [comment]
Hi @venkat2469, I wonder does release engineer has any idea why `1.0.0` is not available through `pip` although it is available on the PyPi page : . https://pypi.org/project/ml-metadata/#history?

**Comment by AlexandreBrown** [comment]
@venkat2469 @BrianSong Hello, any update on this ?

**Comment by rtg0795** [comment]
Hi @AlexandreBrown , may I know the python version you are using to install the ml-metadata package?

**Comment by AlexandreBrown** [comment]
Hello @rtg0795 , using Python 3.9.

**Comment by BrianSong** [comment]
@AlexandreBrown , Python 3.9 is not supported until 1.8.0. Could you try to install 1.8.0 or 1.9.0?

**Comment by AlexandreBrown** [comment]
@BrianSong Unfortunately 1.8 and 1.9 cause errors. I must install a version that is compatible with Kubeflow (v1.4.1).

Kubeflow 1.4.1 uses a database scheme that seems to only work with lower versions like 1.0.

My use case is I want to use ml-metadata to query the mysql database that Kubeflow fills in during experiments (pipeline runs).

![Screenshot_20220816-161926.png](https://user-images.githubusercontent.com/26939775/184977520-d3557810-5f07-46b4-898c-af9bbb0ce295.png)

**Comment by BrianSong** [comment]
I see. Is it possible for you to upgrade Kubeflow with a higher version? v1.4.1 is a pretty old version so it might be compatible with MLMD 1.8.0 and higher. 

Also, downgrading your py version looks like another way to go.

**Comment by AlexandreBrown** [comment]
@BrianSong Well to be quite honest I wouldn't consider Kubeflow `v1.4.1` as "old" since the latest version is `v1.5.1` which [was published only 13 days ago from AWS](https://github.com/awslabs/kubeflow-manifests/releases/tag/v1.5.1-aws-b1.0.1) and upgrading Kubeflow installs can involve much more than a pip install (unfortunately).  
  
I followed your alternative option and downgraded my python version from 3.9 to 3.8 and that did the trick for me.  
  
Would be nice if this detail could be documented for future reference.
