### ISSUE TITLE
Garbage collection of underlying artifacts

### ISSUE THREAD

**Issue by micahjsmith** [google/ml-metadata#162]
Hi team, MLMD artifacts have a state which can be LIVE or DELETED (among other conditions). Should MLMD have any responsibility for detecting when objects underlying artifacts have been deleted such that their state should be changed to DELETED, such as in some sort of GC process that checks for existence of the objects? If not, what would you recommend to MLMD users about how and when to mark objects as deleted?

For context, I'm working on fixing an issue in TFX in which if an object is deleted that underlies an MLMD artifact, the TFX component driver could inappropriately detect a cache hit leading to a situation in which a downstream component tries to access the object indicated from the cache which no longer exists. So one solution we are considering is that when MLMD returns a set of matching output artifacts to a historical execution, TFX doesn't trust the LIVE state and instead verifies that the objects still exists, and updates the state of the artifacts otherwise. However, it would probably more robust if MLMD was responsible for periodically updating artifact states so consumers could trust the results. (Obviously there could still be race conditions.)

**Comment by BrianSong** [comment]
Hi @micahjsmith,

MLMD artifacts are marked as `DELETED` during TFX GC process. MLMD itself does not have any GC process but it is under our radar. 

IIUC from the context, this issue is not only about MLMD but instead it's more about TFX side. Have you raised this issue there?

**Comment by micahjsmith** [comment]
Hi @BrianSong , thanks for your response.

> MLMD artifacts are marked as DELETED during TFX GC process.

I'm not aware of any code path in TFX that does GC or marks artifacts as deleted. TFX publishes artifacts and marks them as LIVE and doesn't do any other updates to artifact state that I'm aware of

> IIUC from the context, this issue is not only about MLMD but instead it's more about TFX side. Have you raised this issue there?

Yes, I've raised this issue with TFX side, and we agree that the ideal long term solution would be for some GC process that is not owned by TFX (but more likely owned by MLMD) to check for missing/deleted artifacts. In the meantime, I have a patch that checks whether artifacts still exist at the time they are accessed: https://github.com/tensorflow/tfx/pull/5093

**Comment by BrianSong** [comment]
>I'm not aware of any code path in TFX that does GC or marks artifacts as deleted. TFX publishes artifacts and marks them as LIVE and doesn't do any other updates to artifact state that I'm aware of

TFX indeed does some GC and mark MLMD artifacts as `DELETED`, however, I cannot find those functions in the TFX Github repo, it seems that they are not OSSed. 

MLMD is happy to help with a better GC though, maybe we can discuss offline? @1025KB @jiyongjung0

**Comment by 1025KB** [comment]
We don't support GC at this point externally, users can use ttl as workaround.

**Comment by micahjsmith** [comment]
I also can't find any record of TTL support in MLMD (I just know of `create_time_since_epoch` and `last_update_time_since_epoch` properties). Can you point me to how OSS users would configure TTL on MLMD artifacts? Thanks

**Comment by casassg** [comment]
Hey @1025KB this is becoming a problem internally. Is there any docs on workaround? CC @rcrowe-google

**Comment by 1025KB** [comment]
sorry, to be clear, I mean ttl of the file system, not from MLMD.

e.g., the path is sth like root/ttl=30d/<pipeline_name>/<component>/<artifact>/*, and the file system will clean based on ttl.

If the underlying file system doesn't support ttl, a workaround can be periodically run a script that scan MLMD to delete old uri

**Comment by casassg** [comment]
@1025KB removing from file system does not delete MLMD which causes TFX to fail. We have 21 days of TTL on our file system, but MLMD is still there even after that (and after the files have been long gone). So essentially that does not solve the problem at hand either

**Comment by rcrowe-google** [comment]
@casassg Thanks for raising this, we're going to be discussing this internally next week.

**Comment by BrianSong** [comment]
I meet with @1025KB and @rcrowe-google today to discuss this issue. The conclusion is: the TFX users should be responsible for creating their own GC process if necessary. 

The reasons are:
- MLMD library does not create/delete the objects/payloads underlying artifacts. The objects/payloads are not under MLMD's control - MLMD only store the metadata. 
- In TFX/MLMD context, "the artifact is deleted due to a deletion process outside of the pipeline" is a user-specific behavior which is unexpected. 

However, it makes sense that the TFX users might want to garbage collect the objects/payloads. The TFX users can create their own GC process and avoiding the "the MLMD artifact’s state is still LIVE but the underlying objects are deleted" problem by using the [`update_artifact_state`](https://github.com/tensorflow/tfx/blob/4a6421b6b99f6529ef2c95437ce3f3f08a5c04d8/tfx/orchestration/metadata.py#L197) API to update the artifact's state to DELETED whenever the underlying objects/payloads are deleted.

**Comment by BrianSong** [comment]
Closed this issue for now, please feel free to reopen it if needed.
