### ISSUE TITLE
How do I get the stack trace?

### ISSUE THREAD

**Issue by streamnsight** [google/ml-metadata#163]
I am having issues with metadata-store-server in a Kubeflow deployment.

When using the full command:
```
/bin/metadata_store_server --grpc_port=8080 \
--mysql_config_database=$MYSQL_DATABASE \
--mysql_config_host=$MYSQL_HOST \
--mysql_config_port=$MYSQL_PORT \
--mysql_config_user=$DBCONFIG_USER \
--mysql_config_password=$DBCONFIG_PASSWORD \
--enable_database_upgrade=true
```

I am getting:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0819 13:16:08.859220    31 metadata_store_server_main.cc:236] Check failed: absl::OkStatus() == status (OK vs. INTERNAL: mysql_real_connect failed: errno: , error:  [mysql-error-info='']) MetadataStore cannot be created with the given connection config.
*** Check failure stack trace: ***
Aborted (core dumped)
```
I tried with the docker image v1.7.0 or 1.5.0 without success. My credentials, host / port are correct as connectivity works with the same secret for another pod.

Note that the output does not show an `errorno` or a `mysql-error-info` string and no stack trace, so that makes it pretty difficult to troubleshoot.

Any suggestions on how to get the error / stack trace to print properly?

**Comment by BrianSong** [comment]
Hi, thanks for bringing this up.

May I wonder what version of mysql are you doing?

**Comment by streamnsight** [comment]
@BrianSong 
I'm using MySQL 8.0.30
The issue seems to be that this project requires authenticating via the mysql_native_password plugin which was not the default on my system.
After creating a user and enforcing the use of mysql_native_password to create the password, it worked.

nevertheless, it would be nice to have a stacktrace to understand what is going on. it is very randomly that I figured this issue.

**Comment by BrianSong** [comment]
Sure. Added https://github.com/google/ml-metadata/commit/d31978731f2654ba77dbb55a3b766ea97ceba27d. Closed this issue for now.
