### ISSUE TITLE
Support SSL in MySQL backend?

### ISSUE THREAD

**Issue by ZxMYS** [google/ml-metadata#20]
Hi! It seems like currently if I want to use MySQL as the backend there’s no way to enable SSL of db connections? (I just briefly skimmed the source code so I might be wrong). 
Can we added optional MySQL SSL configs to connection config and support enabling SSL of MySQL in MLMD? Thanks!

**Comment by hughmiao** [comment]
hi @ZxMYS , mysql client ssl option is not supported yet. We will add the support. 
In the current release, you can also setup a mlmd grpc server and use ssl connection from the grpc client, if it works for you.

**Comment by ZxMYS** [comment]
@hughmiao great! looking forward to it.
Thanks for the suggestion - our MySQL server requires SSL, so I guess even if I set grpc up, the grpc server would still need SSL options in its connection to MySQL.

**Comment by hughmiao** [comment]
True, the server does the same thing. Yes, we need to add the ssl options to mysql connection config.

**Comment by hughmiao** [comment]
this should be fixed on the head. it is also included in the 0.15.1 release. please feel free to reopen if there's other issues.

**Comment by ZxMYS** [comment]
@hughmiao thanks for the quick resolution! Appreciated.
One more request - can we also support configuring the MYSQL_OPT_SSL_MODE option (see https://dev.mysql.com/doc/refman/5.7/en/mysql-options.html)? We'd like to set it to SSL_MODE_VERIFY_IDENTITY.
A related example is that PyMySQL supports a check_hostname flag in its ssl config which does this.

**Comment by hughmiao** [comment]
thanks @ZxMYS  for the feedback. MYSQL_OPT_SSL_MODE looks to me is added in 5.7+. 
Note we rely on libmysql client headers (mariadb-connector-c [1]) to build and test, which is a mariadb implementation on mysql 5.6, where that constant is not defined in the header [1]. On the other hand, MYSQL_OPT_SSL_VERIFY_SERVER_CERT may be possible to add, however it is deprecated in 5.7 and removed in 8. Not sure it works in your environment. Our test env is mariadb 10+ too. We may consider to support `MYSQL_OPT_SSL_VERIFY_SERVER_CERT` in the next release. 

Also if this FR is a blocker for you and waiting for the next release is not ideal, consider to use [mysql_options](https://dev.mysql.com/doc/refman/5.7/en/mysql-options.html) in a similar way as the [commit](https://github.com/google/ml-metadata/commit/ad9e136adac83e7f9eb7bf793d230cb1a2a413e8) does, and build the wheel [from the modified source](https://github.com/google/ml-metadata#3-build-the-pip-package). If set `MYSQL_OPT_SSL_VERIFY_SERVER_CERT` works in your environment, please feel free to send a pull request too. 

[1] https://github.com/MariaDB/mariadb-connector-c/blob/de04c2e01fef13cb4545b85f47fd90ec92f2c95e/include/mysql.h#L166
[2] https://dev.mysql.com/doc/refman/5.7/en/mysql-options.html
