### ISSUE TITLE
Building with bazel 1.1.0 requires several incompatible flags

### ISSUE THREAD

**Issue by ZxMYS** [google/ml-metadata#23]
Hi! When I tried to build ml-metadata with bazel 1.1.0 (`bazel run -c opt --define grpc_no_ares=true ml_metadata:build_pip_package`), I found that these incompatible flags are required:
```
--incompatible_disable_deprecated_attr_params=false 
--incompatible_no_support_tools_in_action_inputs=false 
--incompatible_new_actions_api=false 
--incompatible_string_join_requires_strings=false 
--incompatible_no_rule_outputs_param=false
--incompatible_require_ctx_in_configure_features=false
```
Is there plan to better support bazel 1.1.0? thanks.

**Comment by hughmiao** [comment]
please use bazel 0.24 ~ 0.26. 
we upgrades the bazel version along with tensorflow [1]

[1] https://www.tensorflow.org/install/source#tested_build_configurations

**Comment by hughmiao** [comment]
Close this for now. Please feel free to reopen if there's other build issues.
