### ISSUE TITLE
Consider dropping tensorflow as dependency

### ISSUE THREAD

**Issue by Ark-kun** [google/ml-metadata#25]
Tensorflow is a huge package with many dependencies. It only supports modern CPUs and fails to even import on older ones.

In my opinion, Metadata should be generic and not TF-specific.

**Comment by hughmiao** [comment]
Hi @Ark-kun , thanks. Yes, there are plans to drop the tf dependency ([setup.py](https://github.com/google/ml-metadata/blob/77aa66b2a16d88b2ea836aa67d0881f73591ac16/setup.py#L87)). We currently depends on tf status and error (core/lib) to compile from source, which takes < 5 minutes, hope it's ok in your scenario.

**Comment by Ark-kun** [comment]
I guess my issue lacked some important information. I was talking about the ML-Metadata Python client which downloads and installs gigabytes of tensorflow packages that it does not use.

> hope it's ok in your scenario.

As I said, just `import ml-metadata` produces `Segmentation fault` on non-recent CPUs.
The core CUJ seems to be broken.

**Comment by hughmiao** [comment]
> I was talking about the ML-Metadata Python client which downloads and installs gigabytes of tensorflow packages that it does not use.

I agree the current dependency on tf is undesirable. We currently used tf's py errors in the py client to integrate with tfx-oss. Probably dropping tf's dependency in python as a first step is a good way to go. 

> As I said, just import ml-metadata produces Segmentation fault on non-recent CPUs.
The core CUJ seems to be broken.

was the `Segmentation fault` still there? there was some issue with tf 2.0 in b/146077129. 
missing `libnvinfer` may cause the segmentation fault.  
would you please let us know the details for your deployment setup?

**Comment by Ark-kun** [comment]
>was the Segmentation fault still there?

It's still there and will be there forever since Tensorflow has dropped support for CPUs without AVX instructions. Just trying to load TF will result in that error. https://github.com/tensorflow/tensorflow/issues?utf8=%E2%9C%93&q=is%3Aissue+AVX+ sample issue: https://github.com/tensorflow/tensorflow/issues/34148#issuecomment-552554386

Even for Windows there are hundreds of issue reports (the error message is different)
https://github.com/tensorflow/tensorflow/issues?utf8=%E2%9C%93&q=is%3Aissue+%22ImportError%3A+DLL+load+failed%22

All those people won't be able to import the metadata store.

In general, Tensorflow is big heavy package with many dependencies; its not easy to install, is quite picky about its environment. Making it a dependency for something as small and lite as ml-metadata is inconvenient.

**Comment by hughmiao** [comment]
Thanks for the details, @Ark-kun. Let's reopen this, and deprecate this python layer dependency in the coming releases.
