### ISSUE TITLE
Support for PostgreSQL?

### ISSUE THREAD

**Issue by jnmclarty** [google/ml-metadata#26]
Hi there,

We're wondering about the priority of supporting postgresql.  I have a couple questions for the maintainers.

1.  If a PR was submitted for the initial effort, could the project afford to maintain feature-parity with PostgreSQL?
2.  Does anybody know of a reason this wouldn't be fairly easy to port; I mean, over and above the dialect tweaks?  For instance, are there any mysql-specific features that might impede support?

**Comment by hughmiao** [comment]
Hi @jnmclarty 

> Does anybody know of a reason this wouldn't be fairly easy to port; I mean, over and above the dialect tweaks? For instance, are there any mysql-specific features that might impede support?

There's no mysql-specific features. Supporting postgresSQL requires to provide a [metadata_source](https://github.com/google/ml-metadata/blob/master/ml_metadata/metadata_store/metadata_source.h) (e.g., [sqlite](https://github.com/google/ml-metadata/blob/master/ml_metadata/metadata_store/sqlite_metadata_source.h), [mysql](https://github.com/google/ml-metadata/blob/master/ml_metadata/metadata_store/mysql_metadata_source.h)), and adjust its query [configs](https://github.com/google/ml-metadata/blob/master/ml_metadata/util/metadata_source_query_config.h). The test suite is templated too, simply adding one similar to [this](https://github.com/google/ml-metadata/blob/master/ml_metadata/metadata_store/sqlite_metadata_access_object_test.cc). Also see [issue 17](https://github.com/google/ml-metadata/issues/17#issuecomment-538192251) too for overall guidelines to support a new backend.

> If a PR was submitted for the initial effort, could the project afford to maintain feature-parity with PostgreSQL?

Given PostgreSQL is very popular, for sure, we will keep the feature parity and keep it updated.

**Comment by jnmclarty** [comment]
We are mulling our options.

**Comment by StephenHogg** [comment]
Any progress on this? We're very interested in having a postgres backend

**Comment by jnmclarty** [comment]
Sorry; we went another direction and didn't use this.

**Comment by kwright02** [comment]
@jnmclarty What does "We went another direction" mean in this context? PostgreSQL support should be an industry standard thing given how widely used of a database system it is.

Please re-open this issue

**Comment by maulik-modi22** [comment]
@jnmclarty, Could you please provide latest support statement?
