### ISSUE TITLE
What is the schema_version in MLMD?

### ISSUE THREAD

**Issue by tywtyw** [google/ml-metadata#27]
I am confused about the schema version in MLMD. What is the scheme exactly about? Does it refer to changes in relationships between tables in database?  Hopefully to get a reply.

**Comment by hughmiao** [comment]
@tywtyw apologies for the late reply. 
The `schema_version` is used when migrating the MLMD backend when upgrading MLMD libraries. It is an internal implementation detail to ensure the integrity and consistency of the stored data. When MLMD evolves, it may include breaking changes that change the physical relational tables in the provided backend store. When the user upgrade MLMD to a new version, the old database may not work with the new MLMD library. The user can use the  provided tools to migrate the database. The detailed process is described in [1]. 

[1] https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md#upgrade-mlmd-library
