### ISSUE TITLE
get_contexts(), get_context_types() etc fail with exception when the DB is empty.

### ISSUE THREAD

**Issue by Ark-kun** [google/ml-metadata#28]
`get_contexts()` throws "Cannot find any record".
`get_context_types()` throws "" (which is very confusing).

Expected behavior: the "get all" functions should return empty list when the DB is empty and not throw an exception.

**Comment by hughmiao** [comment]
thanks for the suggestion, @Ark-kun . We will align the API and return [] for get_artifacts/executions/contexts methods. 

For `get_context_types`, currently it already returns []. Would you please help us reproduce the case of throws "" errors ?

**Comment by hughmiao** [comment]
close this issue now. please feel free to reopen.
