### ISSUE TITLE
Support artifact state with MYSQL DB.

### ISSUE THREAD

**Issue by liyzcj** [google/ml-metadata#29]
In Release 0.21.0, Artifact in proto add a state field. But when Connect with MYSQL DB, There are no State field in table Atifact.

We can Create a proto object Artifact with state, but when get this Artifact back from DB, the state will disappear, cause there are **no Artifact state store in DB.**

**Comment by hughmiao** [comment]
hi @liyzcj thanks for your feedback. This is a known issue, and it will be fixed in the coming release. Currently artifact's and execution's state are not stored. Please use `properties` for now.

**Comment by hughmiao** [comment]
this is supported now at head and will be included in the 0.22 release.
