### ISSUE TITLE
Document imports in the Getting started guide

### ISSUE THREAD

**Issue by atn832** [google/ml-metadata#31]
It took me a while to find how to import the dependencies required to run the Getting started code snippets. Can we add this snippet to the guide?

```py
from ml_metadata import metadata_store
from ml_metadata.proto import metadata_store_pb2
```

**Comment by atn832** [comment]
If I send a PR to change https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md, does it get reflected on https://www.tensorflow.org/tfx/guide/mlmd as well?

**Comment by hughmiao** [comment]
@atn832 hi Anh, thanks for the contribution! note www.tensorflow.org/tfx/guide/mlmd is in tfx repo. so the change needs to be made twice. If possible do you mind to send a cl instead a pr. we didnot setup the sync from github yet, and we can point to you the tfx repo doc.

**Comment by atn832** [comment]
@hughmiao Sure, can you show me where that repo is? I'll make a PR for it.

**Comment by hughmiao** [comment]
the doc is tfx/opensource_only/g3doc/guide/mlmd.md
here's an example cl/264242956

**Comment by atn832** [comment]
@hughmiao Please review the 3 PRs at your convenience.
