### ISSUE TITLE
Using the same MySQL db to run more than 1 tfx pipelines

### ISSUE THREAD

**Issue by nadgirsanket** [google/ml-metadata#34]
Let's take an example scenario,

I want to run 1 model per customer. If I have 10 customers, there would be 10 models (10 tfx pipelines).

If I hook up the tfx pipeline in airflow to run 10 tfx pipelines for 10 customers, the artifacts generated and stored in MySQL db are getting mixed between customers/pipelines.

For example, if I have to run the pipeline for 2 customers and the model Evaluator for the 2nd pipeline considers the 1st pipeline's model as a baseline model and 2nd pipeline's model as candidate model.

```
INFO:absl:Using ../../data/artifacts_<customer_2>/Trainer/model/2265/serving_model_dir as candidate model.
INFO:absl:Using ../../data/artifacts_<customer_1>/Trainer/model/1446/serving_model_dir as baseline model.
INFO:absl:Evaluating model.
INFO:absl:Using 1 process(es) for Beam pipeline execution.
WARNING:absl:inputs do not match those expected by the model: input_names=['examples'], found in extracts={}
INFO:absl:Evaluation complete. Results written to ../../data/artifacts_<customer_2>/Evaluator/evaluation/2288.
INFO:absl:Checking validation results.
INFO:absl:Blessing result True written to ../../data/artifacts_<customer_2>/Evaluator/blessing/2288.
INFO:absl:Running publisher for Evaluator
INFO:absl:MetadataStore with DB connection initialized
```

This issue was not there when I was using a file-based SQLite connection. The artifacts were being stored in a separate directory per customer and the pipeline was also identifying them as separate. But SQLite wasn't scalable. Hence, I moved to MYSQL connection.

Is there a way to separately version the Artifacts between multiple pipelines using MySQL connection? If so, please let me know. Or if it's possible to scale file-based SQLite to scale to 1000s of connections, please let me know.

**Comment by hughmiao** [comment]
there's a MLMD pipeline context and pipeline run context used in TFX when running the pipelines.
The mixed artifacts are connected to different contexts corresponding to different pipelines. Please see [1][2][3] for details to retrieve the artifacts by pipelines. 

[1] https://www.tensorflow.org/tfx/guide/mlmd#top_of_page
[2] https://www.tensorflow.org/tfx/ml_metadata/api_docs/python/mlmd/metadata_store/MetadataStore#get_context_types
[3] https://www.tensorflow.org/tfx/ml_metadata/api_docs/python/mlmd/metadata_store/MetadataStore#get_artifacts_by_context
