### ISSUE TITLE
Throws error when running example

### ISSUE THREAD

**Issue by utkobe** [google/ml-metadata#36]
I just follow the example provided in https://www.tensorflow.org/tfx/guide/mlmd. 

it fails at 
```
input_event = metadata_store_pb2.Event()
input_event.artifact_id = data_artifact_id
input_event.execution_id = run_id
input_event.type = metadata_store_pb2.Event.DECLARED_INPUT
```

and gives error
```
Traceback (most recent call last):
  File "test-mlmetadata.py", line 45, in <module>
    input_event.artifact_id = data_artifact_id
TypeError: [2] has type list, but expected one of: int, long
```

it seems that the artifact_id expects a number and instead data_artifact_id is a list with numbers?

**Comment by hughmiao** [comment]
thanks @utkobe . yes, it returns a list. it looks there's some sync problem to the tf's website. we will take a look. please refer to MLMD [get_started.md](https://github.com/google/ml-metadata/blob/master/g3doc/get_started.md#tracking-ml-workflows-with-ml-metadata)
