### ISSUE TITLE
No Python 3.8 version?

### ISSUE THREAD

**Issue by domedagen** [google/ml-metadata#37]
Hi!

I get this error when I'm trying to install the requirements of TFX on local.
`ERROR: Could not find a version that satisfies the requirement ml-metadata<0.22,>=0.21.2 (from tfx==0.22.0.dev0->-r requirements.txt (line 3)) (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0)
`

As I interpret it, it doesn't find any version of ml-metadata above 0.13.1.dev0, [although 0.21.2 on 29 Feb 2020](https://pypi.org/project/ml-metadata/#history). Again, I'm no expert, but this could be because there doesn't seem to be a [version for Python 3.8 released](https://pypi.org/project/ml-metadata/#files).

Could you release a version for Python 3.8? When I try to install the requirements with Python 3.6 it works.

**Comment by domedagen** [comment]
If you look at the top of the readme [![Python](https://img.shields.io/pypi/pyversions/ml-metadata.svg?style=plastic)](https://github.com/google/ml-metadata) it does not actually explicitly include Python 3.8 in the list of supported versions as of now. The same is true for both TensforFlow and TFX. 

There seems to be an [issue about this over at TensorFlow](https://github.com/tensorflow/tensorflow/issues/33374) and it seems to be in progress.

**Comment by hughmiao** [comment]
hi @domedagen , py38 is not supported yet. The released wheels can be found [here](https://pypi.org/project/ml-metadata/0.22.0/#files). We are working on this and will support it in the next release.

**Comment by sm-hawkfish** [comment]
Hi @hughmiao -- bumping this issue as Tensorflow now supports python3.8 . Alternatively, perhaps merging #35 would be a better way to unblock the Python3.8 release of `ml_metadata` ?

**Comment by lihan** [comment]
Can't use TFX on Python 3.8 because of this, is there an short-term fix?

**Comment by hughmiao** [comment]
@lihan TFX does support 3.8 yet, beam and core libs, e.g., tfx-bsl all in 3.7.  To unblock none-tfx mlmd users, we will deprecate py tf dependency via #35 in the coming release (early Aug), and then work on 3.8 wheels.

**Comment by lihan** [comment]
@hughmiao Thanks, I’ve installed Python 3.7 on Conda, and walked around this.

**Comment by sm-hawkfish** [comment]
@hughmiao , is the plan still to release a python3.8 version of ml-metadata this month?

**Comment by hughmiao** [comment]
@sm-hawkfish  just released 0.24.0 which includes py38 wheels. closing the issue.
