### ISSUE TITLE
How to delete an artifact?

### ISSUE THREAD

**Issue by nlarusstone** [google/ml-metadata#38]
I see that you can delete an artifact type by passing in a `put_artifact_type` request with `can_delete_fields` set to true.

However, I don't see how I could delete an artifact without going into the database and manually deleting rows.

Am I missing something?

Thanks!

**Comment by hughmiao** [comment]
delete was not exposed by design, as this is metadata store, if an artifact is Deleted, then the rest of the DAG becomes disconnected. If the entire database is not useful, consider drop the db; if the artifact is abandoned, please mark its `state` as DELETED.
