### ISSUE TITLE
PutAttributionsAndAssociations() error: Context id not found.

### ISSUE THREAD

**Issue by wulikai1993** [google/ml-metadata#39]
ml-metadata version: 0.22.0

```python
attribution = metadata_store_pb2.Attribution()
attribution.artifact_id = model_artifact_id
attribution.context_id = experiment_id

association = metadata_store_pb2.Association()
association.execution_id = run_id
attribution.context_id = experiment_id

request = metadata_store_service_pb2.PutAttributionsAndAssociationsRequest()
request.attributions.append(attribution)
request.associations.append(association)
stub.PutAttributionsAndAssociations(request)
```

The `experiment_id` is 20 here, and I inspect the database, there is the context which id is 20. So why the error occurs and how to solve it?

**Comment by hughmiao** [comment]
hi @wulikai1993 , thanks for the feedback. to reproduce, would you please print all the contexts here?

**Comment by wulikai1993** [comment]
@hughmiao Sorry, I found I made a mistake in line 7 `attribution.context_id = experiment_id`. The `attribution` here should be `association`. After that, the code can run normally. Thanks for your reply!
