### ISSUE TITLE
Support for building the server for alternate linux platforms?

### ISSUE THREAD

**Issue by s-mcqueen** [google/ml-metadata#41]
Currently the Dockerfile used for building and running the server only supports Ubuntu 18.04. I have a use case where I want to run the server (outside of a container) on a CentOS host. Are there any plans for other supported build targets?

I have a Dockerfile that compiles for centos7 that my team at Twitter is using to build the server. If there's interest, I would be happy to commit it upstream.

**Comment by hughmiao** [comment]
thanks, @s-mcqueen , sure, welcome to contribute! :)

> Are there any plans for other supported build targets?

The ubuntu image was derived from bazel images. To support other cases, probably not via docker image like ubuntu. Instead, we'd encourage the users to build from source. Fwiw, that build script should work for most linux environment; we also release manylinux wheels which builds cpp part in a python CentOS image with basic dependencies; the cpp server is a thin layer on the shared cpp lib.

**Comment by s-mcqueen** [comment]
Thanks for the response! That makes sense. On second look, the Dockerfile we are using to compile from source is probably too specific to be committed upstream but it works for our use-case for now. I appreciate the context on this.
