### ISSUE TITLE
ml-metadata image deleted from registry, breaks kubeflow deployments

### ISSUE THREAD

**Issue by yanniszark** [google/ml-metadata#43]
Hi all!
First of all, thanks for your work on `ml-metadata`! :smile:
It's a project we use in Kubeflow for our tracking needs. More specifically, we make use of the following image:
` gcr.io/tfx-oss-public/ml_metadata_store_server:v0.21.1`

However, this image recently disappeared. Was it deleted from the registry?
Because of this, all Kubeflow installations have a broken metadata component and some won't continue at all, as they detect a broken installation.
Is it possible to restore the image until a more permanent solution can be implemented? (like cloning images to a kubeflow registry). Thanks a lot!

**Comment by numerology** [comment]
Took a look and it seems like it's renamed to `gcr.io/tfx-oss-public/ml_metadata_store_server:0.21.1`

**Comment by yanniszark** [comment]
@numerology thanks for the response, that's good to know.
Do you think it would be possible to also restore the old `gcr.io/tfx-oss-public/ml_metadata_store_server:v0.21.1` image until we can change this in upstream Kubeflow given that it breaks current deployments?

**Comment by numerology** [comment]
@yanniszark 

Sure. Done.

**Comment by yanniszark** [comment]
@numerology thanks a lot, that's very helpful :smile: 
Closing this issue as resolved...
