### ISSUE TITLE
[Support] SDK Docs

### ISSUE THREAD

**Issue by alexlatchford** [google/ml-metadata#44]
Been trying to find the SDK documentation for this project, especially how to retrieve metadata that is stored within an MLMD store but drawing a blank. Looks like [the Getting Started guide](https://www.tensorflow.org/tfx/guide/mlmd) does a great job of setting up the store and getting data into the store but I'm curious now how to utilize the data in further steps!

**Comment by hughmiao** [comment]
@alexlatchford thanks for your interests. We are extending get started guide to improve the docs. The query APIs on the data model are those with get_*, which lists nodes and support lineage traversals. Meanwhile, please point to docs at [1][2] for API references. 

[1] https://www.tensorflow.org/tfx/guide/mlmd
[2] https://www.tensorflow.org/tfx/ml_metadata/api_docs/python/mlmd/metadata_store/MetadataStore

**Comment by alexlatchford** [comment]
Ah awesome, definitely just missed the link to [this page](https://www.tensorflow.org/tfx/ml_metadata/api_docs/python/mlmd/metadata_store/MetadataStore), couldn't seem to find it but assumed it must exist somewhere. Thanks for the link.
