### ISSUE TITLE
MySQL - no index on EventPath table

### ISSUE THREAD

**Issue by mattmbk** [google/ml-metadata#53]
It seems that when creating the EventPath table in MySQL there is no index created.

This causes performance to degrade as the amount of data grows in the table (e.g. > 100k rows).

The performance issues were resolved by adding an index:
ALTER TABLE `EventPath` ADD INDEX `event_id_index` (`event_id`);

**Comment by hughmiao** [comment]
thanks, @mattmbk. Yes, some of the query performance tuning needs to be done given the data size increases and new use cases beyond tfx. Apart from building the index, if the performance degrade is related to bulk retrieval of events via get_events_by_artifact/execution calls, the recent commit [01f6231](https://github.com/google/ml-metadata/commit/e1b79a8cfd044c37e620394056d1c809ee3f40af) will help too. It will be included in the coming release.

There's longer term plan to work on the query optimizations, e.g., as a first step, tools/mlmd_bench is under developing to profile different APIs on different supportd backends. stay tuned. :)
