### ISSUE TITLE
pip install does not work with 0.21.1

### ISSUE THREAD

**Issue by ianhellstrom** [google/ml-metadata#56]
When I run `pip install` for the version I need (because of `kubeflow-metadata`) I get an error:

```bash
pip install ml-metadata==0.21.1
ERROR: Could not find a version that satisfies the requirement ml-metadata==0.21.1 (from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0)
ERROR: No matching distribution found for ml-metadata==0.21.1
```

It's supposed to exist, but I have no luck making it work: https://pypi.org/project/ml-metadata/0.21.1/

Other packages work but it fails on `kubeflow-metadata` because of the aforementioned error.

**Comment by hughmiao** [comment]
hi @ianhellstrom  which os/python environment did you use? 0.21.1 has win/mac/manylinux wheels for 27/35/36/37. 
also the pip error looks out of date, if install a wrong version, it report all existing ones: 
```
Could not find a version that satisfies the requirement ml-metadata==0.21.5 
(from versions: 0.12.0.dev0, 0.13.0.dev0, 0.13.1.dev0, 0.13.2, 0.14.0, 0.15.0rc0, 0.15.0, 0.15.1, 0.15.2, 0.21.0rc0, 0.21.0, 0.21.1, 0.21.2, 0.22.0)
```

**Comment by ianhellstrom** [comment]
MacOS 10.15.6
Python 3.8.5

It seems Python 3.8 is the issue. It works with Python 3.7.

**Comment by hughmiao** [comment]
thanks, @ianhellstrom . 3.8 is not supported yet. we will support it in the next release, ETA Sep.
Mark it closed. it is tracked in https://github.com/google/ml-metadata/issues/37
