### ISSUE TITLE
Official/ recommended naming convention for pipelines

### ISSUE THREAD

**Issue by calvinleungyk** [google/ml-metadata#59]
Hi team, are there recommended naming conventions and namespace approaches for pipelines aside from the default interactive + unix timestamp naming that's used?

**Comment by hughmiao** [comment]
Hi, @calvinleungyk  Just saw this. Note the tfx pipeline name should be unique, we don't have an official naming convention; consider to use {org, user, pipeline name, version} to create a meaningful name and avoid conflict with others in the org using the same db instance.
