### ISSUE TITLE
Why not group dataset artifacts to experiments? 

### ISSUE THREAD

**Issue by Jeffwan** [google/ml-metadata#75]
In the last step of official example, it only groups model artifacts to an experiment. I saw a few datasets were created as well. 
I assume all the artifacts should be group to experiment. That means attribution should have same number as artifact type? 

```
# Create a ContextType, e.g., Experiment with a note property
experiment_type = metadata_store_pb2.ContextType()
experiment_type.name = "Experiment"
experiment_type.properties["note"] = metadata_store_pb2.STRING
experiment_type_id = store.put_context_type(experiment_type)

# Group the model and the trainer run to an experiment.
my_experiment = metadata_store_pb2.Context()
my_experiment.type_id = experiment_type_id
# Give the experiment a name
my_experiment.name = "exp1"
my_experiment.properties["note"].string_value = "My first experiment."
experiment_id = store.put_contexts([my_experiment])[0]

# Should we also link all the dataset artifact to the context? 
attribution = metadata_store_pb2.Attribution()
attribution.artifact_id = model_artifact_id
attribution.context_id = experiment_id

association = metadata_store_pb2.Association()
association.execution_id = run_id
association.context_id = experiment_id

store.put_attributions_and_associations([attribution], [association])
```

Another problem I noice it there's no separate methods for `put_attribution` and `put_associations`. Is there a plan to support them separately? Or you think that's unnecessary? 

Currently, we have to use this way
```
store.put_attributions_and_associations([], [association]) -> put_associations()
store.put_attributions_and_associations([attribution], []) -> put_attribution()
```

**Comment by hughmiao** [comment]
@Jeffwan, thanks for the thoughts! The MLMD API is evolving, we are happy to hear your use case and better support those. Please see the comments inline below.

> In the last step of official example, it only groups model artifacts to an experiment. I saw a few datasets were created as well. I assume all the artifacts should be group to experiment. That means attribution should have same number as artifact type?

Yes, conceptual, these can be grouped to the experiment too. It depends on the semantics of the user-defined experiment. Depending on your use case, the attribution / association can be used accordingly.

> Another problem I noice it there's no separate methods for put_attribution and put_associations. Is there a plan to support them separately? Or you think that's unnecessary?

It was not introduced based on the current integration use cases (e.g., tfx). These are often attached together, e.g., a trainer reads data1 and produces model1, so the {input-artifact, execution, output-artifact} tuple are often attached to the same context. Having a single call, these edges are inserted atomically in a single transaction.

You may find `put_execution` [1] useful to attach these edges too. It is a transaction where not only the edges are inserted, but also the contexts/artifacts related to an execution may be upserted together too.

[1] https://www.tensorflow.org/tfx/ml_metadata/api_docs/python/mlmd/metadata_store/MetadataStore#put_execution
