### ISSUE TITLE
Feature request: UI and visualization tools

### ISSUE THREAD

**Issue by danielbraun89** [google/ml-metadata#8]
In the 2019 tf summit presentation about TFX usage of MLMD a couple of visualization and UI tools were shown, to deliver better handling of th mlmd database. such tools help to enable the benefits of mlmd such as artifact history tracking. As of today, with no such tools published, it is up to the developer to write a program that will turn the .db file into something maningful. I advise to release  those tools (already shown in the presentation) to the public

**Comment by rcrowe-google** [comment]
We published an [updated version of the Dev Summit workshop as a self-paced tutorial](https://www.tensorflow.org/tfx/tutorials/tfx/workshop), including the notebooks that show how to interact with ML-Metadata and the visualization tools:

https://www.tensorflow.org/tfx/tutorials/tfx/workshop

**Comment by glenxiao** [comment]
+1 for visualization support. The workshop links above point to TFX Airflow Tutorial. Could you update the links please?

**Comment by hughmiao** [comment]
@glenxiao The workshop code for this tutorial is available at: https://github.com/tensorflow/tfx/tree/master/tfx/examples/airflow_workshop

UI is available if running TFX with kubeflow pipelines:
https://www.kubeflow.org/docs/pipelines/pipelines-quickstart
https://www.tensorflow.org/tfx/tutorials/tfx/cloud-ai-platform-pipelines

**Comment by pritamdodeja** [comment]
If someone is developing pipelines using the local dag runner, how are they supposed to interact with the metadata from a visual/exploratory perspective? Even something graphviz based that shows the interrelationships and some basic metadata would be useful.

**Comment by rcrowe-google** [comment]
A partial answer, but not visual, is to use the MLMD client library from TFX-Addons:

https://github.com/tensorflow/tfx-addons/tree/main/tfx_addons/mlmd_client
