### ISSUE TITLE
Context.type missing in metadata_store_pb2.Context Python class

### ISSUE THREAD

**Issue by viscrisn** [google/ml-metadata#88]
Hello team,
I am working with [metadata_store_pb2.Context](https://github.com/google/ml-metadata/blob/master/ml_metadata/proto/metadata_store.proto#L301 ) and am trying to get ContextType name from context. 

When I do `get_contexts_by_execution` after putting context types and contexts, I do not get context.type in the return structure. 
context.type_id is populated and correct. Is this expected behavior? 

In my code I have to filter for specific `ContextType` in returned list of `Context`. The workaround I am using is to create a dictionary of `context type_id` and `context name` and then use this map to match with `ContextType name`
```
context_types = get_context_types_by_id([context.type_id for context in contexts])
context_types_map = {context_type.id: context_type.name for context_type in context_types}
```

To put context type I am calling 
```
context_type = metadata_store_pb2.ContextType()
context_type.name = "NewContext"
put_context_type([context_type])
```

To put in context I am using 
```
put_contexts(list of contexts)
```

**Comment by hughmiao** [comment]
@viscrisn this is WAI in the current release. Only `type_id` is returned.  

> When I do get_contexts_by_execution
> In my code I have to filter for specific ContextType in returned list of Context.

if filtering a single type `name`, consider to use `get_context_type(type_name)` which returns the type obj with `id` and defined properties. 

If a map is needed, note you can also use `get_context_types()` to return all stored context types to create the dict.

**Comment by viscrisn** [comment]
I see. I am assuming it's a design decision and we should get context type name on our own. We'll use it accordingly. Can you tell us where to look at for current structure definition for reference? This still seems to have "type" in structure: https://github.com/google/ml-metadata/blob/master/ml_metadata/proto/metadata_store.proto#L291 (I checked other release branches as well)

**Comment by hughmiao** [comment]
> Can you tell us where to look at for current structure definition for reference? This still seems to have "type" in structure: https://github.com/google/ml-metadata/blob/master/ml_metadata/proto/metadata_store.proto#L291 (I checked other release branches as well)

The proto link is the right one. All fields in proto is optional. Currently the type name is not populated when returning it in the releases. One can reuse the proto definition, and set the type if needed.

> I see. I am assuming it's a design decision and we should get context type name on our own. We'll use it accordingly. 

Yes, fwiw, there was some discussion before on whether `type` should be returned by default, pros is usability of the api, cons is an extra a join and deprecating id based apis. We may populate the type in the future releases. For now, you can always wrap a util over the lower level mlmd apis, and set the type in the returned proto if needed by doing a lookup.

**Comment by viscrisn** [comment]
Thank you for quick and helpful replies.
