### ISSUE TITLE
Support read only access in MLMD

### ISSUE THREAD

**Issue by daikeshi** [google/ml-metadata#96]
We tried to deploy MLMD grpc server on top of a CloudSQL instance read-only replica, so our users can safely read the metadata stored in MLMD. However, `MetadataStoreServer` initialization results in the following error: 
```
2020-12-16 14:58:20.340073: F ml_metadata/metadata_store/metadata_store_server_main.cc:220] Non-OK-status: status status: Internal: mysql_query failed: errno: 1290, error: The MySQL server is running with the --read-only option so it cannot execute this statement
```

It seems MLMD always tries to [create the database](https://github.com/google/ml-metadata/blob/master/ml_metadata/metadata_store/mysql_metadata_source.cc#L153) which requires db creation privilege. I wonder if it's possible we can do a database existence check first before creating the database, so read-only users can also connect to MLMD with the metadata store?

**Comment by hughmiao** [comment]
@daikeshi thanks for letting us know the deployment issue with CloudSQL. That looks a good feature to have. would you like to contribute a PR? if this is urgent for you, you can also build custom server to bypass that [1] to see whether it works for you. Note after the create db, if it is empty, it needs to init schema by create tables and indices if not exists. You may still need a mlmd instance with create privilege to populate the tables for you. If the db and table both exist, then the new  connection does not need ddl. 

[1] https://github.com/google/ml-metadata/tree/master/ml_metadata/tools/docker_server

**Comment by daikeshi** [comment]
@hughmiao sounds good! I'll take a stab at it.
