### ISSUE TITLE
TFX ML Metadata storage to PostgreSQL

### ISSUE THREAD

**Issue by cah-aswini-jalla** [google/ml-metadata#98]
I wanted to store my metadata information of ML artifacts to PostgreSQL but I couldn't find any libraries that support MLMD for PostgreSQL. Is there any API's that could support to PostgreSQL other than MySQL/SQLite?

**Comment by hughmiao** [comment]
It only supports MySQL/SQLite at the moment. Please take a look at https://github.com/google/ml-metadata/issues/26, and also https://github.com/google/ml-metadata/issues/17 if you are interested in extending the library.
